### ISSUE TITLE
large ensembles with > 3 dimensions fail

### ISSUE THREAD

**Issue by studywolf** [project-rig/nengo_spinnaker#115]
I'm getting this error (again on the `new_ensembles-new-learning` branch)

``` bash
Traceback (most recent call last):
  File "scrap.py", line 15, in <module>
    sim.run(100)
  File "/home/pawel/src/nengo_spinnaker/nengo_spinnaker/simulator.py", line 190, in run
    self.run_steps(steps)
  File "/home/pawel/src/nengo_spinnaker/nengo_spinnaker/simulator.py", line 196, in run_steps
    self._run_steps(n_steps)
  File "/home/pawel/src/nengo_spinnaker/nengo_spinnaker/simulator.py", line 260, in _run_steps
    len(self.netlist.vertices))
  File "/home/pawel/src/nengo_spinnaker/nengo_spinnaker/simulator.py", line 292, in _wait_for_transition
    raise Exception("Unexpected core failures before reaching %s state." % desired_to_state)
Exception: Unexpected core failures before reaching AppState.sync0 state.
```

using this code 

``` python
import nengo
import numpy as np

model = nengo.Network()
with model: 
    # ens = nengo.Ensemble(n_neurons=2000, dimensions=3) # doesn't fail
    ens = nengo.Ensemble(n_neurons=2000, dimensions=4) # fails

import nengo_spinnaker
import logging
logging.basicConfig(level=logging.DEBUG)
nengo_spinnaker.add_spinnaker_params(model.config)
sim = nengo_spinnaker.Simulator(model)
print 'model built.'

sim.run(100)
```

I haven't actually tried with fewer neurons but it's real late and i'm tired! :dash:

**Comment by tcstewar** [comment]
> I haven't actually tried with fewer neurons but it's real late and i'm tired!

Just for context, we did try it with 1000 neurons and 6 dimensions, and that worked fine.....  But we didn't figure out where the neuron limit is before it dies.

**Comment by studywolf** [comment]
Right!

**Comment by neworderofjamie** [comment]
That sounds very much like a memory error (basically one of the cores
failed to malloc the memory it desired). I imagine one of partitioning
heuristics has gone awry - I'll investigate.

**Comment by neworderofjamie** [comment]
@studywolf are you building executables or using the ones that were in git? The git ones were SO out of date, I'd be surprised anything works so I've submitted a new set - can you try again? That code snippet works fine for me

**Comment by studywolf** [comment]
Ah! I thought I had done that just recently but I will try again and double check once I'm in today!

**Comment by studywolf** [comment]
Hmm OK so are you on the 'new_ensemble-new-learning' branch? that's where I get the error. it doesn't throw it on master, though!

**Comment by studywolf** [comment]
whooooooop! it's working after another pull! thanks!
