### ISSUE TITLE
Node removal breaks under Python 3

### ISSUE THREAD

**Issue by mundya** [project-rig/nengo_spinnaker#123]
Should be calling `toposort_flatten` with `sort=False`, I think. More investigation required.

**Comment by tcstewar** [comment]
Hmm, yup, that's happening for me too on spinnaker models (including the spa-sequence example).  Your suggested fix solves it for me!

**Comment by mundya** [comment]
If you want to submit a fix... ;-)

**Comment by mundya** [comment]
(I'm away from SpiNNaker at the moment, sorry)

**Comment by mundya** [comment]
This has been fixed in master (since `toposort_flatten` is no longer used).
