### ISSUE TITLE
Error when using nengo version 2.4.0

### ISSUE THREAD

**Issue by azadef** [project-rig/nengo_spinnaker#157]
When using nengo_spinnaker along with nengo version 2.4.0, there is an error in ensemble.py file:
module 'ensemble' has no attribute 'sample'. When I downgraded nengo to version 2.2.0 the problem was solved.

**Comment by tcstewar** [comment]
Argh, sorry about that.  That's an ongoing problem with the core of nengo -- we still haven't really nailed down exactly what parts of the internals of nengo should be part of our fixed API that other projects like nengo_spinnaker can rely on.  But thank you for pointing this one out!  I'll see if I can quickly fix this (we probably just renamed a function....)

**Comment by tcstewar** [comment]
I just added a fix-ensemble-sample branch which might fix this.  I can't test it right now as I'm at home and don't have a SpiNNaker board with me, but I'll try it in the morning.

**Comment by azadef** [comment]
Thank you very much for the fast fix
