### ISSUE TITLE
Store binaries in the repo

### ISSUE THREAD

**Issue by mundya** [project-rig/nengo_spinnaker#26]
This is something that I normally think is a Bad Thing :tm: but would be useful for @celiasmith and @studywolf among others.  @neworderofjamie, would you have any problem moving to us storing binaries in the repository and ensuring that we keep them up-to-date with the branches they are related to?

**Comment by mossblaser** [comment]
I would like to 2nd this having lost some time this afternoon to having out-of-sync binaries in my local checkout!
