### ISSUE TITLE
Nengo Spinnaker not matching expected results

### ISSUE THREAD

**Issue by pabogdan** [project-rig/nengo_spinnaker#39]
I've written this small script to play around with transforms. The idea is that the output point is supposed to be rotated by 180&deg; around the origin. When running with Nengo backend the both the input and output follow the outline of the unit circle (as expected). When running on Nengo SpiNNaker both the input and output follow a very flattened ellipse either oriented on the X or Y axis.

This has been tested using nengo_gui.

``` python
import nengo
import numpy as np

model = nengo.Network("Rotation")

with model:
    tau = 0.1
    x_in = nengo.Node(output=np.sin)
    y_in = nengo.Node(output=np.cos)
    rotation = nengo.Ensemble(n_neurons=300, dimensions=2, radius=1.2)

    output = nengo.Ensemble(n_neurons=300, dimensions=2, radius=1.2)
    nengo.Connection(x_in, rotation[0])
    nengo.Connection(y_in, rotation[1])
    nengo.Connection(rotation, output, transform=[[-1, 0], [0, -1]])
```

**Comment by mundya** [comment]
Can you try this instead?

``` python
import nengo
import numpy as np

model = nengo.Network("Rotation")

with model:
    tau = 0.1
    xy_in = nengo.Node(output=lambda t: [np.sin(t), np.cos(t)])
    rotation = nengo.Ensemble(n_neurons=300, dimensions=2, radius=1.2)

    output = nengo.Ensemble(n_neurons=300, dimensions=2, radius=1.2)
    nengo.Connection(xy_in, rotation)
    nengo.Connection(rotation, output, transform=[[-1, 0], [0, -1]])
```

I suspect that what you're seeing might be sampling being applied differently to the two nodes so combining them into one should avoid that.

**Comment by pabogdan** [comment]
This worked!

**Comment by mundya** [comment]
Noted that the communication between the PC and SpiNNaker during simulation needs improving!
